### ISSUE TITLE
Could not connect to docker: reached retry deadline from CircleCI

### ISSUE THREAD

**Issue by TranLuongTuanAnh** [ory/dockertest#267]
Locally it's all working, but when I run it in CircleCI I get this error: `Could not connect to docker: reached retry deadline`
In CI I configured `setup_remote_docker`
I also checked DOCKER_HOST value , it was set such as tcp://35.231.51.115:2376.

This is My code 
```
	// uses a sensible default on windows (tcp/http) and linux/osx (socket)
	log.Println(os.Getenv("DOCKER_HOST"))
	pool, err := dockertest.NewPool("")
	if err != nil {
		log.Fatalf("Could not connect to docker: %s", err)
	}

	// pulls an image, creates a container based on it and runs it
	resource, err := pool.BuildAndRun("mysql", "../../db/image/Dockerfile", []string{})
	if err != nil {
		log.Fatalf("Could not start resource: %s", err)
	}
```

CI config.yml

```
version: 2.1
executors:
  go-executor:
    docker:
      - image: circleci/golang:1.16.3
    working_directory: ~/workspace
jobs:
  dependencies:
    executor: go-executor
    parameters:
      env:
        type: enum
        enum: ["pro", "stg", "dev", "test"]
    steps:
      - checkout
      - restore_cache: &restore-cache
          keys:
            - go-module-cache-v1-{{ .Branch }}-{{ checksum "go.mod" }}
            - go-module-cache-v1-{{ .Branch }}
            - go-module-cache-v1-
      - run: go mod download
      - save_cache:
          key: go-module-cache-v1-{{ .Branch }}-{{ checksum "go.mod" }}
          paths:
            - /go/pkg/mod/cache
      - persist_to_workspace:
          root: ../
          paths:
            - ./workspace
  test:
    executor: go-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - attach_workspace:
          at: ..
      - run:
          command: make test
```
